name: Build Love2D Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install FUSE
      - name: Install FUSE
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse

      # Step 4: Install Love2D
      - name: Install Love2D
        run: |
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-x86_64.AppImage -O love2d.AppImage
          chmod +x love2d.AppImage
          sudo mv love2d.AppImage /usr/local/bin/love
          love2d --version


      # Step 5: Download appimagetool
      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage

      # Step 6: Add appimagetool to PATH
      - name: Add appimagetool to PATH
        run: |
          sudo mv appimagetool.AppImage /usr/local/bin/appimagetool
          echo "appimagetool is in PATH:"
          which appimagetool
          appimagetool --version

      # Step 7: Install makelove
      - name: Install makelove
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install makelove

      # Step 8: Build Love2D project
      - name: Build Love2D project
        run: |
          mkdir -p builds
          makelove --config makelove.toml

      # Step 9: Compress build outputs
      - name: Compress build outputs
        run: |
          cd builds
          zip -r love.zip love
          zip -r lovejs.zip lovejs
          zip -r love-appimage.zip appimage

      # Step 10: Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: |
            builds/love.zip
            builds/lovejs.zip
            builds/love-appimage.zip
