name: Build Love2D Project

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Install FUSE
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage

      - name: Add appimagetool to PATH
        run: |
          sudo mv appimagetool.AppImage /usr/local/bin/appimagetool
          echo "appimagetool is in PATH:"
          which appimagetool
          appimagetool --version

      - name: Install makelove
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install makelove

  build_project:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Build Love2D project
        run: |
          mkdir -p builds
          makelove --config makelove.toml

  compress_outputs:
    runs-on: ubuntu-latest
    needs: build_project

    steps:
      - name: Compress build outputs
        run: |
          cd builds
          zip -r love.zip love
          zip -r lovejs.zip lovejs
          zip -r love-appimage.zip appimage

  release:
    runs-on: ubuntu-latest
    needs: compress_outputs

    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: |
            builds/love.zip
            builds/lovejs.zip
            builds/love-appimage.zip
