              # - name: Love actions for Linux
              #   uses: love-actions/love-actions-linux@v1.2.2
            
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Love actions for Linux
        uses: love-actions/love-actions-linux@v1.2.2