name: Build Love2D Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: main
          submodules: true

      # Step 2: Install system dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes wine-stable wine64 python3-pip fuse

      # Step 3: Checkout makelove
      - name: Checkout makelove
        uses: actions/checkout@v2
        with:
          repository: pfirsich/makelove
          path: makelove

      # Step 4: Install makelove
      - name: Install makelove
        run: |
          pip3 install ./makelove

      # Step 5: Download Love2D AppImage
      - name: Download Love2D AppImage
        run: |
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-x86_64.AppImage -O love.AppImage
          chmod +x love.AppImage
          ./love.AppImage --appimage-extract

      # Step 6: Run makelove to build the Love2D project
      - name: Build Love2D project
        run: |
          cd main/game
          python3 -m makelove

      # Step 7: Prepare Artifact Names
      - name: Prepare Artifact Names
        run: |
          echo "::set-env name=ARTIFACT_NAME_LOVE::$(ls main/makelove-build/love | head -n1)"
          echo "::set-env name=ARTIFACT_NAME_APPIMAGE::$(ls main/makelove-build/appimage | head -n1)"
          echo "::set-env name=ARTIFACT_NAME_WIN64::$(ls main/makelove-build/win64 | head -n1)"
          echo "::set-env name=ARTIFACT_NAME_MACOS::$(ls main/makelove-build/macos | head -n1)"

      # Step 8: Upload Artifact (Love2D)
      - name: Artifact (Love)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME_LOVE }}
          path: main/makelove-build/love/${{ env.ARTIFACT_NAME_LOVE }}

      # Step 9: Upload Artifact (AppImage)
      - name: Artifact (AppImage)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME_APPIMAGE }}
          path: main/makelove-build/appimage/${{ env.ARTIFACT_NAME_APPIMAGE }}

      # Step 10: Upload Artifact (Win64)
      - name: Artifact (Win64)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME_WIN64 }}
          path: main/makelove-build/win64/${{ env.ARTIFACT_NAME_WIN64 }}

      # Step 11: Upload Artifact (MacOS)
      - name: Artifact (MacOS)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME_MACOS }}
          path: main/makelove-build/macos/${{ env.ARTIFACT_NAME_MACOS }}
