name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Linux packages
        id: build-packages
        uses: love-action/love-actions-linux@v2
        with:
          app-name: Love App
          bundle-id: com.example.loveapp
          description: My awesome love app
          version-string: "1.0.0"
          icon-path: ./.github/build/linux/dev/icon.png
          love-ref: "11.5"
          love-package: ./game.love
          lib-path: ./lib
          share-path: ./share
          build-deb: true
          product-name: love_app
          output-folder: ./dist
