name: Build Love2D Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify makelove.toml exists
        run: |
          if [ ! -f "makelove.toml" ]; then
            echo "makelove.toml not found in the repository!"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install makelove
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install makelove

      - name: Download appimagetool
        run: |
          wget -O appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Set appimagetool path
        run: |
          echo "APPIMAGE_TOOL_PATH=$(pwd)/appimagetool-x86_64.AppImage" >> $GITHUB_ENV

      - name: Build Love2D project
        run: |
          mkdir -p bin # Garantir que a pasta de saída exista
          makelove --config makelove.toml

      - name: Compress build outputs
        run: |
          zip -r bin/appimage.zip bin/appimage
          zip -r bin/love.zip bin/love
          zip -r bin/lovejs.zip bin/lovejs

      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: |
            bin/appimage.zip
            bin/love.zip
            bin/lovejs.zip
